copyright: "©1993-2017 Kx Systems, Inc. Kx® and kdb+ are registered trademarks of Kx Systems, Inc., a subsidiary of First Derivatives plc."
dev_addr: '0.0.0.0:8000'
docs_dir: 'docs'
extra_css: 
  - stylesheets/extra.css
extra_javascript: 
  - 'https://code.jquery.com/jquery-3.1.1.min.js'
  - 'https://use.fontawesome.com/3dbf29ed12.js'
  - scripts/fdtracker.js
  - scripts/googleanalytics.js
  - scripts/theme.js
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - codehilite(guess_lang=false)
    - extra
    - fontawesome_markdown
    - pymdownx.arithmatex
    # - pymdownx.betterem(smart_enable=all)
    # - pymdownx.caret
    # - pymdownx.critic
    # - pymdownx.emoji:
        # emoji_generator: !!python/name:pymdownx.emoji.to_svg
    # - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    # - pymdownx.smartsymbols
    - pymdownx.superfences
    # - pymdownx.tasklist(custom_checkbox=true)
    # - pymdownx.tilde
    - toc(permalink=true)
site_dir: 'site'
site_author: 'Kx Systems'
site_description: Resources for kdb+ programmers
site_favicon: './img/favicon.ico'
# config.site_name: 'code.kx.com'
site_name: 'code.kx.com'
site_url: 'http://code.kx.com'
remote_branch: 'master'
# repo_name: 'GitHub'
# repo_url: 'https://github.com/kxsystems/docs'
theme: 'material'
# theme_dir for favicon
#theme_dir: 'theme'
extra:
  logo: 'img/kx.jpeg'
  palette: 
    primary: 'blue'
    accent: 'deep orange'
  # version: '0.1.0'
pages:
  - Home: index.md
  - Get started: learn.md
  - Reference card: reference.md
  - Reference: 
    - Elements: reference/elements.md
    - Syntax: reference/syntax.md
    - Datatypes: reference/datatypes.md
    - Glossary: reference/glossary.md
    - Semantics:
      - Adverbs: reference/adverbs.md
      - Arithmetic (integer): reference/arithmetic-integer.md
      - Arithmetic (float): reference/arithmetic-float.md
      - Casting: reference/casting.md
      - Comparison: reference/comparisonfunctions.md
      - Dictionaries & tables: reference/dictionariesandtables.md
      - Enumeration: reference/enumeration.md
      - Evaluation control: reference/evaluationcontrol.md
      - Error handling: reference/errors.md
      - Files (numbers): reference/filenumbers.md
      - Files (words): reference/filewords.md
      - Functional SQL: reference/functionalsql.md
      - Joins: reference/joins.md
      - Lists: reference/listfunctions.md
      - Logic: reference/logicfunctions.md
      - Matrixes: reference/matrixes.md
      - Metadata: reference/metadata.md
      - OS: reference/os.md
      - Parallel processing: reference/peach.md
      - Parse trees: reference/parsetrees.md
      - Q-SQL: reference/qsqlfunctions.md
          #   - exec: reference/exec.md
      - Randomness: reference/randomness.md
      - Selection: reference/selectionfunctions.md
      - Search: reference/searchfunctions.md
      - Sort: reference/sortfunctions.md
      - Statistics (aggregates): reference/stats-aggregates.md
      - Statistics (moving): reference/stats-moving.md
      - Text: reference/textfunctions.md
      - Trigonometry: reference/trigonometry.md
      - Unclassified: reference/unclassified.md
    - Command line: reference/commandline.md
    - IPC protocol: reference/ipcprotocol.md
    - System commands: reference/systemcommands.md
    - System utilities:
        - .h namespace: reference/doth.md
        - .Q namespace: reference/dotq.md
        - .z namespace: reference/dotz.md
        - Developer tools: reference/developertools.md
        - Internal functions: reference/internalfunctions.md
    - Releases:
      - Changes in 3.4: reference/releases/ChangesIn3.4.md
      - Changes in 3.3: reference/releases/ChangesIn3.3.md
      - Changes in 3.2: reference/releases/ChangesIn3.2.md
      - Changes in 3.1: reference/releases/ChangesIn3.1.md
      - Changes in 3.0: reference/releases/ChangesIn3.0.md
      - Changes in 2.8: reference/releases/ChangesIn2.8.md
      - Changes in 2.7: reference/releases/ChangesIn2.7.md
      - Changes in 2.6: reference/releases/ChangesIn2.6.md
      - Changes in 2.5: reference/releases/ChangesIn2.5.md
      - Changes in 2.4: reference/releases/ChangesIn2.4.md
      - Withdrawn: reference/withdrawn.md
    # - Unclassified:
    #   - IPC protocol: reference/ipcprotocol.md
    #   - par.txt: reference/pardottxt.md
  - Cookbook:
    - Regular expressions: cookbook/regex.md
  - Developer: developer.md
  - Q for Mortals 3: qformortals3.md
  - Archive: archive.md
  - About: 
    - This site: about/thissite.md
    - Kx technology: about/kxtechnology.md
    - Terms & conditions: about/TermsAndConditions.md
