copyright: "©1993-2017 Kx Systems, Inc. Kx® and kdb+ are registered trademarks of Kx Systems, Inc., a subsidiary of First Derivatives plc."
dev_addr: '0.0.0.0:8000'
docs_dir: 'docs'
extra_css: 
  - stylesheets/extra.css
extra_javascript: 
  - 'https://code.jquery.com/jquery-3.1.1.min.js'
  - scripts/fdtracker.js
  - scripts/googleanalytics.js
  - scripts/theme.js
  # - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML'
# google_analytics: ['UA-3462586-4','kx.com', 'code.kx.com']
markdown_extensions:
    - admonition
    - codehilite(guess_lang=false)
    - extra
    - pymdownx.arithmatex
    # - pymdownx.betterem(smart_enable=all)
    # - pymdownx.caret
    # - pymdownx.critic
    # - pymdownx.emoji:
        # emoji_generator: !!python/name:pymdownx.emoji.to_svg
    # - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    # - pymdownx.smartsymbols
    - pymdownx.superfences
    # - pymdownx.tasklist(custom_checkbox=true)
    # - pymdownx.tilde
    - toc(permalink=true)
site_dir: 'site'
site_author: 'Kx Systems'
site_description: Resources for kdb+ programmers
site_favicon: './img/favicon.ico'
# config.site_name: 'code.kx.com'
site_name: 'code.kx.com'
site_url: 'http://code.kx.com'
remote_branch: 'master'
# repo_name: 'GitHub'
# repo_url: 'https://github.com/kxsystems/docs'
theme: 'material'
# theme_dir for favicon
#theme_dir: 'theme'
extra:
  logo: 'img/kx.jpeg'
  palette: 
    primary: 'blue'
    accent: 'deep orange'
  # version: '0.1.0'
pages:
  - Home: index.md
  - Get started: learn.md
  - Reference card: reference.md
  - Language: 
    - Syntax: language/syntax.md
    - Datatypes: language/datatypes.md
    - Operators: language/operators.md
    - Functions: language/functions.md
    - Higher-order functions: language/higher-order-functions.md
    - Releases:
      - Changes in 3.4: language/releases/ChangesIn3.4.md
      - Changes in 3.3: language/releases/ChangesIn3.3.md
      - Changes in 3.2: language/releases/ChangesIn3.2.md
      - Changes in 3.1: language/releases/ChangesIn3.1.md
      - Changes in 3.0: language/releases/ChangesIn3.0.md
      - Changes in 2.8: language/releases/ChangesIn2.8.md
      - Changes in 2.7: language/releases/ChangesIn2.7.md
      - Changes in 2.6: language/releases/ChangesIn2.6.md
      - Changes in 2.5: language/releases/ChangesIn2.5.md
      - Changes in 2.4: language/releases/ChangesIn2.4.md
  - Functions by use:
      # - ampersand: language/Ampersand.md
      # - apostrophe: language/Apostrophe.md
      # - apostrophecolon: language/ApostropheColon.md
      # - asterisk: language/Asterisk.md
      # - at: language/AtSymbol.md
      # - backslash: language/BackSlash.md
      # - backslash backslash: language/BackSlashBackSlash.md
      # - backslash colon: language/BackSlashColon.md
      # - backtick: language/Backtick.md
      # - bang: language/BangSymbol.md
      # - bang internal function: language/BangSymbolInternalFunction.md
      # - bar: language/Bar.md
      # - brackets: language/Brackets.md
      # - caret: language/Caret.md
      # - colon: language/Colon.md
      # - colon colon: language/ColonColon.md
      # - comma: language/Comma.md
      # - Comparatives: language/Comparatives.md
      # - curly braces: language/CurlyBraces.md
      # - dollar: language/DollarSign.md
      # - dot: language/DotSymbol.md
      # - equals: language/EqualsSymbol.md
      # - LeftRightAngleBracket: language/LeftRightAngleBracket.md
      # - MinusSymbol: language/MinusSymbol.md
      # - NumberSign: language/NumberSign.md
      # - Parentheses: language/Parentheses.md
      # - PercentSymbol: language/PercentSymbol.md
      # - PlusSymbol: language/PlusSymbol.md
      # - QuestionSymbol: language/QuestionSymbol.md
      # - Semicolon: language/Semicolon.md
      # - Slash: language/Slash.md
      # - SlashColon: language/SlashColon.md
      # - Tilde: language/Tilde.md
      # - Underscore: language/Underscore.md
    # - Numbers:
    #   - Zero: language/Zero.md
    #   - ZeroColon: language/ZeroColon.md
    #   - One: language/One.md
    #   - OneColon: language/OneColon.md
    #   - Two: language/Two.md
    #   - TwoColon: language/TwoColon.md
    - Handling lists: language/listfunctions.md
    #   - all: language/all.md
    #   - and: language/and.md
    #   - any: language/any.md
    #   - asc: language/asc.md
    #   - bin: language/bin.md
    #   - count: language/count.md
    #   - cross: language/cross.md
    #   - cut: language/cut.md
    #   - desc: language/desc.md
    #   - differ: language/differ.md
    #   - distinct: language/distinct.md
    #   - enlist: language/enlist.md
    #   - except: language/except.md
    #   - fills: language/fills.md
    #   - first: language/first.md
    #   - flip: language/flip.md
    #   - iasc: language/iasc.md
    #   - idesc: language/idesc.md
    #   - in: language/in.md
    #   - inter: language/inter.md
    #   - last: language/last.md
    #   - next: language/next.md
    #   - prev: language/prev.md
    #   - rank: language/rank.md
    #   - raze: language/raze.md
    #   - reverse: language/reverse.md
    #   - rotate: language/rotate.md
    #   - sublist: language/sublist.md
    #   - sv: language/sv.md
    #   - vs: language/vs.md
    #   - where: language/where.md
    #   - within: language/within.md
    #   - xprev: language/xprev.md
    # - Dictionaries and tables:
    #   - aj: language/aj.md
    #   - asin: language/asin.md
    #   - asof: language/asof.md
    #   - atan: language/atan.md
    #   - cols: language/cols.md
    #   - delete: language/delete.md
    #   - ej: language/ej.md
      # - exec: language/exec.md
    #   - fby: language/fby.md
    #   - fkeys: language/fkeys.md
    #   - group: language/group.md
    #   - ij: language/ij.md
    #   - insert: language/insert.md
    #   - key: language/key.md
    #   - keys: language/keys.md
    #   - lj: language/lj.md
    #   - meta: language/meta.md
    #   - pj: language/pj.md
    #   - select: language/select.md
    #   - tables: language/tables.md
    #   - uj: language/uj.md
    #   - ungroup: language/ungroup.md
    #   - union: language/union.md
    #   - update: language/update.md
    #   - upsert: language/upsert.md
    #   - view: language/view.md
    #   - views: language/views.md
    #   - wj: language/wj.md
    #   - xasc: language/xasc.md
    #   - xcol: language/xcol.md
    #   - xcols: language/xcols.md
    #   - xdesc: language/xdesc.md
    #   - xgroup: language/xgroup.md
    #   - xkey: language/xkey.md
    - Controlling evaluation: 
      - Control words: language/controlwords.md
      - Handling errors: language/handlingerrors.md
      - Iteration: language/higher-order-functions.md
      - Parallel each: language/peach.md
      - Parse trees: language/handlingparsetrees.md
    - Files: language/files.md
    # - Numbers and logic: 
    #   - abs: language/abs.md
    #   - acos: language/acos.md
    #   - avg: language/avg.md
    #   - avgs: language/avgs.md
    #   - ceiling: language/ceiling.md
    #   - cor: language/cor.md
    #   - cos: language/cos.md
    #   - cov: language/cov.md
    #   - deltas: language/deltas.md
    #   - dev: language/dev.md
    #   - div: language/div.md
    #   - ema: language/ema.md
    #   - exp: language/exp.md
    #   - floor: language/floor.md
    #   - inv: language/inv.md
    #   - log: language/log.md
    #   - lsq: language/lsq.md
    #   - mavg: language/mavg.md
    #   - max: language/max.md
    #   - maxs: language/maxs.md
    #   - mcount: language/mcount.md
    #   - mdev: language/mdev.md
    #   - med: language/med.md
    #   - min: language/min.md
    #   - mins: language/mins.md
    #   - mmax: language/mmax.md
    #   - mmin: language/mmin.md
    #   - mmu: language/mmu.md
    #   - mod: language/mod.md
    #   - msum: language/msum.md
    #   - neg: language/neg.md
    #   - not: language/not.md
    #   - null: language/null.md
    #   - or: language/or.md
    #   - prd: language/prd.md
    #   - prds: language/prds.md
    #   - rand: language/rand.md
    #   - ratios: language/ratios.md
    #   - reciprocal: language/reciprocal.md
    #   - scov: language/scov.md
    #   - sdev: language/sdev.md
    #   - signum: language/signum.md
    #   - sin: language/sin.md
    #   - sqrt: language/sqrt.md
    #   - sum: language/sum.md
    #   - sums: language/sums.md
    #   - svar: language/svar.md
    #   - tan: language/tan.md
    #   - til: language/til.md
    #   - var: language/var.md
    #   - wavg: language/wavg.md
    #   - wsum: language/wsum.md
    #   - xbar: language/xbar.md
    #   - xexp: language/xexp.md
    #   - xlog: language/xlog.md
    #   - xrank: language/xrank.md
    # - OS: 
    #   - getenv: language/getenv.md
    #   - gtime: language/gtime.md
    #   - ltime: language/ltime.md
    #   - setenv: language/setenv.md
    #   - system: language/system.md
    - Text: language/textfunctions.md
    # - Values: 
    #   - attr: language/attr.md
    #   - show: language/show.md
    #   - type: language/type.md
    #   - value: language/value.md
    # - Deprecated or disabled:
    #   - list: language/list.md
    #   - ljf: language/lj.md
    #   - plist: language/plist.md
    #   - txf: language/txf.md
    # - Namespaces:
    #   - doth:
    #     - PLACEHOLDER: dummy.md
    #   - dotQ:
    #     - dotQ.MAP: language/DotQDotMAP.md
    #     - qdotfs: language/qdotfs.md
    #     - dotQ.qp: language/DotQDotqp.md
    #     - dotQ.view: language/DotQDotview.md
    #   - dotz:
    #     - dotzdotN: language/dotzdotN.md
    #     - dotzdota: language/dotzdota.md
    #     - dotzdotac: language/dotzdotac.md
    #     - dotzdotb: language/dotzdotb.md
    #     - dotzdote: language/dotzdote.md
    #     - dotzdotexit: language/dotzdotexit.md
    #     - dotzdotf: language/dotzdotf.md
    #     - dotzdoth: language/dotzdoth.md
    #     - dotzdoti: language/dotzdoti.md
    #     - dotzdotk: language/dotzdotk.md
    #     - dotzdotl: language/dotzdotl.md
    #     - dotzdoto: language/dotzdoto.md
    #     - dotzdotp: language/dotzdotp.md
    #     - dotzdotpc: language/dotzdotpc.md
    #     - dotzdotpd: language/dotzdotpd.md
    #     - dotzdotpg: language/dotzdotpg.md
    #     - dotzdotph: language/dotzdotph.md
    #     - dotzdotpi: language/dotzdotpi.md
    #     - dotzdotpm: language/dotzdotpm.md
    #     - dotzdotpo: language/dotzdotpo.md
    #     - dotzdotpp: language/dotzdotpp.md
    #     - dotzdotps: language/dotzdotps.md
    #     - dotzdotpw: language/dotzdotpw.md
    #     - dotzdots: language/dotzdots.md
    #     - dotzdotts: language/dotzdotts.md
    #     - dotzdotu: language/dotzdotu.md
    #     - dotzdotvs: language/dotzdotvs.md
    #     - dotzdotw: language/dotzdotw.md
    #     - dotzdotwc: language/dotzdotwc.md
    #     - dotzdotwo: language/dotzdotwo.md
    #     - dotzdotws: language/dotzdotws.md
    #     - dotzdotx: language/dotzdotx.md
    #     - dotzdotz: language/dotzdotz.md
    #     - dotzdotzd: language/dotzdotzd.md
    # - Command-line options and system commands:
    #   - Sysa: language/Sysa.md
    #   - Sysb: language/Sysb.md
    #   - Syscmdc: language/Syscmdc.md
    #   - Sysf: language/Sysf.md
    #   - System Commands: language/SystemCommands.md
    #   - Sysv: language/Sysv.md
    # - Cmdline: 
    #   - Overview: language/Cmdline.md
    #   - CmdlineC: language/CmdlineC.md
    #   - CmdlineP: language/CmdlineP.md
    #   - Cmdlineb: language/Cmdlineb.md
    #   - Cmdlineq: language/Cmdlineq.md
    # - Notes on grammar:
    #   - Adverb: language/Adverb.md
    #   - Atoms and Lists: language/AtomList.md
    #   - Associations and Dictionaries: language/AssocDict.md
    #   - Function: language/Function.md
    #   - Glossary: language/glossary.md
    #   - Grammar: language/Grammar.md
    #   - Language: language/language.md
    #   - Nouns: language/Nouns.md
    #   - Number: language/Number.md
    #   - Parse tree: language/parse_tree.md
    #   - Table: language/Table.md
    # - Unclassified:
    #   - Console Size: language/ConsoleSize.md
    #   - Display Precision: language/DisplayPrecision.md
    #   - IPC protocol: language/ipcprotocol.md
    #   - Joins: language/joins.md
    #   - par.txt: language/pardottxt.md
  - Cookbook:
    - Regular expressions: cookbook/regex.md
  - Developer: developer.md
  - Q for Mortals 3: qformortals3.md
  - Archive: archive.md
  - About: 
    - Kx technology: about/kxtechnology.md
    - Terms & conditions: about/TermsAndConditions.md
