copyright: "©1993-2017 Kx Systems, Inc. Kx® and kdb+ are registered trademarks of Kx Systems, Inc., a subsidiary of First Derivatives plc."
dev_addr: '0.0.0.0:8000'
docs_dir: 'docs'
extra_css: 
  - stylesheets/extra.css
extra_javascript: 
  - 'https://code.jquery.com/jquery-3.1.1.min.js'
  - 'https://use.fontawesome.com/3dbf29ed12.js'
  - scripts/fdtracker.js
  - scripts/googleanalytics.js
  - scripts/theme.js
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - codehilite(guess_lang=false)
    - extra
    - fontawesome_markdown
    - pymdownx.arithmatex
    # - pymdownx.betterem(smart_enable=all)
    # - pymdownx.caret
    # - pymdownx.critic
    # - pymdownx.emoji:
        # emoji_generator: !!python/name:pymdownx.emoji.to_svg
    # - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    # - pymdownx.smartsymbols
    - pymdownx.superfences
    # - pymdownx.tasklist(custom_checkbox=true)
    # - pymdownx.tilde
    - toc(permalink=true)
site_dir: 'site'
site_author: 'Kx Systems'
site_description: Resources for kdb+ programmers
site_favicon: './img/favicon.ico'
# config.site_name: 'code.kx.com'
site_name: 'code.kx.com'
site_url: 'http://code.kx.com'
remote_branch: 'master'
# repo_name: 'GitHub'
# repo_url: 'https://github.com/kxsystems/docs'
theme: 'material'
# theme_dir for favicon
#theme_dir: 'theme'
extra:
  logo: 'img/kx.jpeg'
  palette: 
    primary: 'blue'
    accent: 'deep orange'
  # version: '0.1.0'
pages:
  - Home: index.md
  - Get started: learn.md
  - Reference card: reference.md
  - Reference: 
    - Elements: language/elements.md
    - Syntax: language/syntax.md
    - Datatypes: language/datatypes.md
    - Glossary: language/glossary.md
    - Semantics:
      - Adverbs: language/adverbs.md
      - Arithmetic (integer): language/arithmetic-integer.md
      - Arithmetic (float): language/arithmetic-float.md
      - Casting: language/casting.md
      - Comparison: language/comparisonfunctions.md
      - Developer tools: language/developertools.md
      - Dictionaries & tables: language/dictionariesandtables.md
      - Enumeration: language/enumeration.md
      - Evaluation control: language/evaluationcontrol.md
      - Error handling: language/errors.md
      - Files (numbers): language/filenumbers.md
      - Files (words): language/filewords.md
      - Functional SQL: language/functionalsql.md
      - Internal functions: language/internalfunctions.md
      - Joins: language/joins.md
      - Lists: language/listfunctions.md
      - Logic: language/logicfunctions.md
      - Matrixes: language/matrixes.md
      - OS: language/os.md
      - Parallel processing: language/peach.md
      - Parse trees: language/parsetrees.md
      - Q-SQL functions: language/qsqlfunctions.md
          #   - exec: language/exec.md
      - Randomness: language/randomness.md
      - Selection: language/selectionfunctions.md
      - Search: language/searchfunctions.md
      - Sort: language/sortfunctions.md
      - Statistics (aggregates): language/stats-aggregates.md
      - Statistics (moving): language/stats-moving.md
      - Text: language/textfunctions.md
      - Trigonometry: language/trigonometry.md
      - Unclassified: language/unclassified.md
    - Command line: language/commandline.md
    - System commands: language/SystemCommands.md
    - System utilities:
        - .h namespace: language/doth.md
        - .Q namespace: language/dotq.md
        - .z namespace: language/dotz.md
    - Releases:
      - Changes in 3.4: language/releases/ChangesIn3.4.md
      - Changes in 3.3: language/releases/ChangesIn3.3.md
      - Changes in 3.2: language/releases/ChangesIn3.2.md
      - Changes in 3.1: language/releases/ChangesIn3.1.md
      - Changes in 3.0: language/releases/ChangesIn3.0.md
      - Changes in 2.8: language/releases/ChangesIn2.8.md
      - Changes in 2.7: language/releases/ChangesIn2.7.md
      - Changes in 2.6: language/releases/ChangesIn2.6.md
      - Changes in 2.5: language/releases/ChangesIn2.5.md
      - Changes in 2.4: language/releases/ChangesIn2.4.md
      - Withdrawn: language/withdrawn.md
    # - Q-SQL:
        # - Meta:
        #   - attr: language/attr.md
        #   - cols: language/cols.md
        #   - fkeys: language/fkeys.md
        #   - key: language/key.md
        #   - keys: language/keys.md
        #   - meta: language/meta.md
        #   - show: language/show.md
        #   - tables: language/tables.md
        #   - type: language/type.md
        #   - value: language/value.md
        #   - view: language/view.md
        #   - views: language/views.md
        # - Sort & group:    
        #   - fby: language/fby.md
        #   - group: language/group.md
        #   - ungroup: language/ungroup.md
        #   - union: language/union.md
        #   - where: language/where.md
        #   - xasc: language/xasc.md
        #   - xcol: language/xcol.md
        #   - xcols: language/xcols.md
        #   - xdesc: language/xdesc.md
        #   - xgroup: language/xgroup.md
        #   - xkey: language/xkey.md
    # - Values: 
    # - Namespaces:
    #   - doth:
    #     - PLACEHOLDER: dummy.md
    #   - dotQ:
    #     - dotQ.MAP: language/DotQDotMAP.md
    #     - qdotfs: language/qdotfs.md
    #     - dotQ.qp: language/DotQDotqp.md
    #     - dotQ.view: language/DotQDotview.md
    #   - dotz:
    #     - dotzdotN: language/dotzdotN.md
    #     - dotzdota: language/dotzdota.md
    #     - dotzdotac: language/dotzdotac.md
    #     - dotzdotb: language/dotzdotb.md
    #     - dotzdote: language/dotzdote.md
    #     - dotzdotexit: language/dotzdotexit.md
    #     - dotzdotf: language/dotzdotf.md
    #     - dotzdoth: language/dotzdoth.md
    #     - dotzdoti: language/dotzdoti.md
    #     - dotzdotk: language/dotzdotk.md
    #     - dotzdotl: language/dotzdotl.md
    #     - dotzdoto: language/dotzdoto.md
    #     - dotzdotp: language/dotzdotp.md
    #     - dotzdotpc: language/dotzdotpc.md
    #     - dotzdotpd: language/dotzdotpd.md
    #     - dotzdotpg: language/dotzdotpg.md
    #     - dotzdotph: language/dotzdotph.md
    #     - dotzdotpi: language/dotzdotpi.md
    #     - dotzdotpm: language/dotzdotpm.md
    #     - dotzdotpo: language/dotzdotpo.md
    #     - dotzdotpp: language/dotzdotpp.md
    #     - dotzdotps: language/dotzdotps.md
    #     - dotzdotpw: language/dotzdotpw.md
    #     - dotzdots: language/dotzdots.md
    #     - dotzdotts: language/dotzdotts.md
    #     - dotzdotu: language/dotzdotu.md
    #     - dotzdotvs: language/dotzdotvs.md
    #     - dotzdotw: language/dotzdotw.md
    #     - dotzdotwc: language/dotzdotwc.md
    #     - dotzdotwo: language/dotzdotwo.md
    #     - dotzdotws: language/dotzdotws.md
    #     - dotzdotx: language/dotzdotx.md
    #     - dotzdotz: language/dotzdotz.md
    #     - dotzdotzd: language/dotzdotzd.md
    # - Command-line options and system commands:
    #   - Sysa: language/Sysa.md
    #   - Sysb: language/Sysb.md
    #   - Syscmdc: language/Syscmdc.md
    #   - Sysf: language/Sysf.md
    #   - Sysv: language/Sysv.md
    # - Cmdline: 
    #   - Overview: language/Cmdline.md
    #   - CmdlineC: language/CmdlineC.md
    #   - CmdlineP: language/CmdlineP.md
    #   - Cmdlineb: language/Cmdlineb.md
    #   - Cmdlineq: language/Cmdlineq.md
    # - Notes on grammar:
    #   - Adverb: language/Adverb.md
    #   - Atoms and Lists: language/AtomList.md
    #   - Associations and Dictionaries: language/AssocDict.md
    #   - Grammar: language/Grammar.md
    #   - Language: language/language.md
    #   - Nouns: language/Nouns.md
    #   - Parse tree: language/parse_tree.md
    #   - Table: language/Table.md
    # - Unclassified:
    #   - Console Size: language/ConsoleSize.md
    #   - Display Precision: language/DisplayPrecision.md
    #   - IPC protocol: language/ipcprotocol.md
    #   - par.txt: language/pardottxt.md
  - Cookbook:
    - Regular expressions: cookbook/regex.md
  - Developer: developer.md
  - Q for Mortals 3: qformortals3.md
  - Archive: archive.md
  - About: 
    - This site: about/thissite.md
    - Kx technology: about/kxtechnology.md
    - Terms & conditions: about/TermsAndConditions.md
