copyright: "©1993-2017 Kx Systems, Inc. Kx® and kdb+ are registered trademarks of Kx Systems, Inc., a subsidiary of First Derivatives plc."
dev_addr: '0.0.0.0:8000'
docs_dir: 'docs'
extra_css: [stylesheets/extra.css]
extra_javascript: [scripts/fdtracker.js,scripts/googleanalytics.js]
# extra_javascript: [scripts/fdtracker.js]
# google_analytics: ['UA-3462586-4','kx.com', 'code.kx.com']
markdown_extensions:
    - extra
site_dir: 'site'
site_author: 'Kx Systems'
site_description: Resources for kdb+ programmers
site_favicon: 'img/favicon.ico'
# config.site_name: 'code.kx.com'
site_name: 'code.kx.com'
site_url: 'http://code.kx.com'
remote_branch: 'master'
# repo_name: 'GitHub'
# repo_url: 'https://github.com/kxsystems/docs'
theme: 'material'
# theme_dir for favicon
#theme_dir: 'theme'
extra:
  logo: 'img/kx.jpeg'
  palette: 
    primary: 'blue'
    accent: 'deep orange'
  # version: '0.1.0'
pages:
  - Home: index.md
  - Get started: learn.md
  - Reference: 
    - Overview: reference/index.md
    - Releases:
      - Changes in 3.4: reference/releases/ChangesIn3.4.md
      - Changes in 3.3: reference/releases/ChangesIn3.3.md
      - Changes in 3.2: reference/releases/ChangesIn3.2.md
      - Changes in 3.1: reference/releases/ChangesIn3.1.md
      - Changes in 3.0: reference/releases/ChangesIn3.0.md
      - Changes in 2.8: reference/releases/ChangesIn2.8.md
      - Changes in 2.7: reference/releases/ChangesIn2.7.md
      - Changes in 2.6: reference/releases/ChangesIn2.6.md
      - Changes in 2.5: reference/releases/ChangesIn2.5.md
      - Changes in 2.4: reference/releases/ChangesIn2.4.md
  - Developer: developer.md
  - Q for Mortals 3: qformortals3.md
  - Archive: archive.md
  - About: 
    - Terms & conditions: about/TermsAndConditions.md
